version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - "8888:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PG_USER}", "-d", "${PG_DBNAME}" ]
      interval: 1s
      retries: 20
    environment:
      POSTGRES_DB: "${PG_DBNAME}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    container_name: postgres-films
    volumes:
      - films_postgresql_data:/var/lib/postgresql/data/
    networks:
      - films_pg_net

volumes:
  films_postgresql_data: null

networks:
  films_internet:
    name: acquaintance_internet
    driver: bridge
  films_pg_net:
    name: acquaintance_pg_net
    driver: bridge